# Generated by Django 2.0.7 on 2018-07-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_years',
            field=models.CharField(default='2018', max_length=250),
        ),
    ]
