# Generated by Django 2.0.7 on 2018-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_education_education_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_year',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
