# Generated by Django 2.0.7 on 2018-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_work_work_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_dev',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_dev',
            field=models.CharField(default='', max_length=250),
        ),
    ]
