# Generated by Django 2.0.7 on 2018-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_auto_20180730_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
