# Generated by Django 2.0.7 on 2018-07-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
